// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jars.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredJars = `-- name: DeleteExpiredJars :exec
DELETE FROM scrolljar WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredJars(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredJars)
	return err
}

const deleteJar = `-- name: DeleteJar :exec
DELETE FROM scrolljar WHERE id = $1
`

func (q *Queries) DeleteJar(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteJar, id)
	return err
}

const getJar = `-- name: GetJar :one
SELECT id, name, user_id, access, password_hash, tags, expires_at, created_at, updated_at
FROM scrolljar
WHERE id = $1 AND (expires_at IS NULL OR expires_at > now())
`

func (q *Queries) GetJar(ctx context.Context, id string) (Scrolljar, error) {
	row := q.db.QueryRow(ctx, getJar, id)
	var i Scrolljar
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.Access,
		&i.PasswordHash,
		&i.Tags,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJarOwnerID = `-- name: GetJarOwnerID :one
SELECT user_id FROM scrolljar
WHERE id = $1 AND (expires_at IS NULL OR expires_at > now())
`

func (q *Queries) GetJarOwnerID(ctx context.Context, id string) (pgtype.Int8, error) {
	row := q.db.QueryRow(ctx, getJarOwnerID, id)
	var user_id pgtype.Int8
	err := row.Scan(&user_id)
	return user_id, err
}

const getJarsByUser = `-- name: GetJarsByUser :many
SELECT id, name, user_id, access, password_hash, tags, expires_at, created_at, updated_at
FROM scrolljar
WHERE user_id = $1 AND (expires_at IS NULL OR expires_at > now())
`

func (q *Queries) GetJarsByUser(ctx context.Context, userID pgtype.Int8) ([]Scrolljar, error) {
	rows, err := q.db.Query(ctx, getJarsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scrolljar
	for rows.Next() {
		var i Scrolljar
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserID,
			&i.Access,
			&i.PasswordHash,
			&i.Tags,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertJar = `-- name: InsertJar :one
INSERT INTO scrolljar (id, user_id, name, access, password_hash, tags, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, user_id, access, password_hash, tags, expires_at, created_at, updated_at
`

type InsertJarParams struct {
	ID           string
	UserID       pgtype.Int8
	Name         pgtype.Text
	Access       int16
	PasswordHash pgtype.Text
	Tags         []string
	ExpiresAt    pgtype.Timestamptz
}

func (q *Queries) InsertJar(ctx context.Context, arg InsertJarParams) (Scrolljar, error) {
	row := q.db.QueryRow(ctx, insertJar,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Access,
		arg.PasswordHash,
		arg.Tags,
		arg.ExpiresAt,
	)
	var i Scrolljar
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.Access,
		&i.PasswordHash,
		&i.Tags,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
