// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	DeleteExpiredJars(ctx context.Context) error
	DeleteExpiredTokens(ctx context.Context) error
	DeleteJar(ctx context.Context, id string) error
	DeleteScroll(ctx context.Context, id string) error
	DeleteTokenByHash(ctx context.Context, tokenHash []byte) error
	DeleteUserTokens(ctx context.Context, userID int64) error
	GetExistingScrollIDs(ctx context.Context, dollar_1 []string) ([]string, error)
	GetJar(ctx context.Context, id string) (Scrolljar, error)
	GetJarOwnerID(ctx context.Context, id string) (pgtype.Int8, error)
	GetJarsByUser(ctx context.Context, userID pgtype.Int8) ([]Scrolljar, error)
	GetScroll(ctx context.Context, id string) (Scroll, error)
	GetScrollsByJar(ctx context.Context, jarID string) ([]Scroll, error)
	GetTokenByHash(ctx context.Context, tokenHash []byte) (GetTokenByHashRow, error)
	GetUserByEmail(ctx context.Context, email string) (UserAccount, error)
	GetUserByID(ctx context.Context, id int64) (UserAccount, error)
	InsertJar(ctx context.Context, arg InsertJarParams) (Scrolljar, error)
	InsertScroll(ctx context.Context, arg InsertScrollParams) (Scroll, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (UserAccount, error)
	SetScrollUploaded(ctx context.Context, arg SetScrollUploadedParams) (pgtype.Timestamptz, error)
	UpdateScroll(ctx context.Context, arg UpdateScrollParams) (pgtype.Timestamptz, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (pgtype.Timestamptz, error)
	UpsertToken(ctx context.Context, arg UpsertTokenParams) error
}

var _ Querier = (*Queries)(nil)
