// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scrolls.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteScroll = `-- name: DeleteScroll :exec
DELETE FROM scroll WHERE id = $1
`

func (q *Queries) DeleteScroll(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteScroll, id)
	return err
}

const getExistingScrollIDs = `-- name: GetExistingScrollIDs :many
SELECT id FROM scroll WHERE id = ANY($1::TEXT[])
`

func (q *Queries) GetExistingScrollIDs(ctx context.Context, dollar_1 []string) ([]string, error) {
	rows, err := q.db.Query(ctx, getExistingScrollIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScroll = `-- name: GetScroll :one
SELECT s.id, s.jar_id, s.title, s.format, s.uploaded, s.created_at, s.updated_at
FROM scroll s
JOIN scrolljar j ON j.id = s.jar_id
WHERE s.id = $1 AND (j.expires_at IS NULL OR j.expires_at > now())
`

func (q *Queries) GetScroll(ctx context.Context, id string) (Scroll, error) {
	row := q.db.QueryRow(ctx, getScroll, id)
	var i Scroll
	err := row.Scan(
		&i.ID,
		&i.JarID,
		&i.Title,
		&i.Format,
		&i.Uploaded,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScrollsByJar = `-- name: GetScrollsByJar :many
SELECT s.id, s.jar_id, s.title, s.format, s.uploaded, s.created_at, s.updated_at
FROM scroll s
JOIN scrolljar j ON j.id = s.jar_id
WHERE s.jar_id = $1 AND s.uploaded = TRUE AND (j.expires_at IS NULL OR j.expires_at > now())
`

func (q *Queries) GetScrollsByJar(ctx context.Context, jarID string) ([]Scroll, error) {
	rows, err := q.db.Query(ctx, getScrollsByJar, jarID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scroll
	for rows.Next() {
		var i Scroll
		if err := rows.Scan(
			&i.ID,
			&i.JarID,
			&i.Title,
			&i.Format,
			&i.Uploaded,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertScroll = `-- name: InsertScroll :one
INSERT INTO scroll (id, jar_id, title, format)
VALUES ($1, $2, $3, $4)
RETURNING id, jar_id, title, format, uploaded, created_at, updated_at
`

type InsertScrollParams struct {
	ID     string
	JarID  string
	Title  pgtype.Text
	Format pgtype.Text
}

func (q *Queries) InsertScroll(ctx context.Context, arg InsertScrollParams) (Scroll, error) {
	row := q.db.QueryRow(ctx, insertScroll,
		arg.ID,
		arg.JarID,
		arg.Title,
		arg.Format,
	)
	var i Scroll
	err := row.Scan(
		&i.ID,
		&i.JarID,
		&i.Title,
		&i.Format,
		&i.Uploaded,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setScrollUploaded = `-- name: SetScrollUploaded :one
UPDATE scroll
SET uploaded = TRUE
WHERE id = $1 AND updated_at = $2
RETURNING updated_at
`

type SetScrollUploadedParams struct {
	ID        string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) SetScrollUploaded(ctx context.Context, arg SetScrollUploadedParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, setScrollUploaded, arg.ID, arg.UpdatedAt)
	var updated_at pgtype.Timestamptz
	err := row.Scan(&updated_at)
	return updated_at, err
}

const updateScroll = `-- name: UpdateScroll :one
UPDATE scroll
SET title = $1, format = $2
WHERE id = $3 AND updated_at = $4
RETURNING updated_at
`

type UpdateScrollParams struct {
	Title     pgtype.Text
	Format    pgtype.Text
	ID        string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateScroll(ctx context.Context, arg UpdateScrollParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, updateScroll,
		arg.Title,
		arg.Format,
		arg.ID,
		arg.UpdatedAt,
	)
	var updated_at pgtype.Timestamptz
	err := row.Scan(&updated_at)
	return updated_at, err
}
