// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredTokens = `-- name: DeleteExpiredTokens :exec
DELETE FROM token WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredTokens)
	return err
}

const deleteTokenByHash = `-- name: DeleteTokenByHash :exec
DELETE FROM token WHERE token_hash = $1
`

func (q *Queries) DeleteTokenByHash(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteTokenByHash, tokenHash)
	return err
}

const deleteUserTokens = `-- name: DeleteUserTokens :exec
DELETE FROM token WHERE user_id = $1
`

func (q *Queries) DeleteUserTokens(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserTokens, userID)
	return err
}

const getTokenByHash = `-- name: GetTokenByHash :one
SELECT user_id, scope, expires_at
FROM token
WHERE token_hash = $1 AND (expires_at IS NULL OR expires_at > now())
`

type GetTokenByHashRow struct {
	UserID    int64
	Scope     string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) GetTokenByHash(ctx context.Context, tokenHash []byte) (GetTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getTokenByHash, tokenHash)
	var i GetTokenByHashRow
	err := row.Scan(&i.UserID, &i.Scope, &i.ExpiresAt)
	return i, err
}

const upsertToken = `-- name: UpsertToken :exec
INSERT INTO token (token_hash, user_id, expires_at, scope)
VALUES ($1, $2, $3, $4)
ON CONFLICT ON CONSTRAINT unique_user_scope_token
DO UPDATE SET
    token_hash = $1,
    expires_at = $3
`

type UpsertTokenParams struct {
	TokenHash []byte
	UserID    int64
	ExpiresAt pgtype.Timestamptz
	Scope     string
}

func (q *Queries) UpsertToken(ctx context.Context, arg UpsertTokenParams) error {
	_, err := q.db.Exec(ctx, upsertToken,
		arg.TokenHash,
		arg.UserID,
		arg.ExpiresAt,
		arg.Scope,
	)
	return err
}
