// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, activated, created_at, updated_at
FROM user_account
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (UserAccount, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Activated,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, activated, created_at, updated_at
FROM user_account
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (UserAccount, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Activated,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO user_account (username, email, password_hash)
VALUES ($1, $2, $3)
RETURNING id, username, email, password_hash, activated, created_at, updated_at
`

type InsertUserParams struct {
	Username     string
	Email        string
	PasswordHash string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (UserAccount, error) {
	row := q.db.QueryRow(ctx, insertUser, arg.Username, arg.Email, arg.PasswordHash)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Activated,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE user_account
SET username = $1, email = $2, activated = $3, password_hash = $4
WHERE id = $5 AND updated_at = $6
RETURNING updated_at
`

type UpdateUserParams struct {
	Username     string
	Email        string
	Activated    bool
	PasswordHash string
	ID           int64
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Username,
		arg.Email,
		arg.Activated,
		arg.PasswordHash,
		arg.ID,
		arg.UpdatedAt,
	)
	var updated_at pgtype.Timestamptz
	err := row.Scan(&updated_at)
	return updated_at, err
}
